# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APIRequestModule' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'RxAlamofire'
  pod 'Alamofire'
  # Pods for APIRequestModule

  target 'APIRequestModuleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'APIRequestModuleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
